// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _mandelbrot_HH_
#define _mandelbrot_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mandelbrot_dadddsbkb.h"
#include "mandelbrot_dadd_6cud.h"
#include "mandelbrot_dmul_6dEe.h"
#include "mandelbrot_ddiv_6eOg.h"
#include "mandelbrot_dcmp_6fYi.h"
#include "mandelbrot_sitodpg8j.h"
#include "mandelbrot_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct mandelbrot : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const2;
    sc_signal< sc_lv<64> > ap_var_for_const3;
    sc_signal< sc_lv<64> > ap_var_for_const4;
    sc_signal< sc_lv<5> > ap_var_for_const5;


    // Module declarations
    mandelbrot(sc_module_name name);
    SC_HAS_PROCESS(mandelbrot);

    ~mandelbrot();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mandelbrot_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* mandelbrot_AXILiteS_s_axi_U;
    mandelbrot_dadddsbkb<1,5,64,64,64>* mandelbrot_dadddsbkb_U1;
    mandelbrot_dadd_6cud<1,5,64,64,64>* mandelbrot_dadd_6cud_U2;
    mandelbrot_dmul_6dEe<1,6,64,64,64>* mandelbrot_dmul_6dEe_U3;
    mandelbrot_dmul_6dEe<1,6,64,64,64>* mandelbrot_dmul_6dEe_U4;
    mandelbrot_dmul_6dEe<1,6,64,64,64>* mandelbrot_dmul_6dEe_U5;
    mandelbrot_ddiv_6eOg<1,31,64,64,64>* mandelbrot_ddiv_6eOg_U6;
    mandelbrot_ddiv_6eOg<1,31,64,64,64>* mandelbrot_ddiv_6eOg_U7;
    mandelbrot_dcmp_6fYi<1,1,64,64,1>* mandelbrot_dcmp_6fYi_U8;
    mandelbrot_sitodpg8j<1,6,32,64>* mandelbrot_sitodpg8j_U9;
    mandelbrot_sitodpg8j<1,6,32,64>* mandelbrot_sitodpg8j_U10;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<72> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > cx;
    sc_signal< sc_lv<32> > cy;
    sc_signal< sc_lv<32> > tmp_6_reg_86;
    sc_signal< sc_lv<64> > t_reg_98;
    sc_signal< sc_lv<64> > y_reg_110;
    sc_signal< sc_lv<64> > grp_fu_133_p2;
    sc_signal< sc_lv<64> > reg_186;
    sc_signal< sc_lv<1> > ap_CS_fsm_state43;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > icmp_reg_323;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage10;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage19;
    sc_signal< sc_lv<64> > grp_fu_138_p2;
    sc_signal< sc_lv<64> > reg_192;
    sc_signal< sc_lv<64> > grp_fu_122_p2;
    sc_signal< sc_lv<64> > reg_198;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage14;
    sc_signal< sc_lv<64> > grp_fu_178_p1;
    sc_signal< sc_lv<64> > tmp_reg_293;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > grp_fu_182_p1;
    sc_signal< sc_lv<64> > tmp_3_reg_298;
    sc_signal< sc_lv<64> > grp_fu_162_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_303;
    sc_signal< sc_lv<1> > ap_CS_fsm_state37;
    sc_signal< sc_lv<64> > grp_fu_167_p2;
    sc_signal< sc_lv<64> > tmp_4_reg_308;
    sc_signal< sc_lv<64> > dcx_reg_313;
    sc_signal< sc_lv<1> > ap_CS_fsm_state48;
    sc_signal< sc_lv<64> > grp_fu_127_p2;
    sc_signal< sc_lv<64> > dcy_reg_318;
    sc_signal< sc_lv<1> > icmp_fu_216_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_lv<64> > grp_fu_147_p2;
    sc_signal< sc_lv<32> > tmp_6_op_fu_222_p2;
    sc_signal< sc_lv<32> > tmp_6_op_reg_332;
    sc_signal< sc_lv<64> > y_1_reg_337;
    sc_signal< sc_lv<32> > tmp_16_fu_270_p3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage22;
    sc_signal< sc_lv<32> > tmp_6_phi_fu_90_p4;
    sc_signal< sc_lv<64> > t_phi_fu_102_p4;
    sc_signal< sc_lv<64> > y_phi_fu_114_p4;
    sc_signal< sc_lv<1> > ap_CS_fsm_state73;
    sc_signal< sc_lv<64> > grp_fu_122_p0;
    sc_signal< sc_lv<64> > grp_fu_122_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state44;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage6;
    sc_signal< sc_lv<64> > grp_fu_127_p0;
    sc_signal< sc_lv<64> > grp_fu_127_p1;
    sc_signal< sc_lv<64> > grp_fu_133_p0;
    sc_signal< sc_lv<64> > grp_fu_133_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state38;
    sc_signal< sc_lv<64> > grp_fu_138_p0;
    sc_signal< sc_lv<64> > grp_fu_138_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<24> > tmp_7_fu_206_p4;
    sc_signal< sc_lv<64> > tmp_14_to_int_fu_228_p1;
    sc_signal< sc_lv<11> > tmp_17_fu_232_p4;
    sc_signal< sc_lv<52> > tmp_18_fu_242_p1;
    sc_signal< sc_lv<1> > notrhs_fu_252_p2;
    sc_signal< sc_lv<1> > notlhs_fu_246_p2;
    sc_signal< sc_lv<1> > tmp_19_fu_258_p2;
    sc_signal< sc_lv<1> > tmp_20_fu_172_p2;
    sc_signal< sc_lv<1> > tmp_21_fu_264_p2;
    sc_signal< sc_lv<2> > grp_fu_122_opcode;
    sc_signal< sc_lv<72> > ap_NS_fsm;
    sc_signal< sc_lv<32> > ap_return;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<72> ap_ST_fsm_state1;
    static const sc_lv<72> ap_ST_fsm_state2;
    static const sc_lv<72> ap_ST_fsm_state3;
    static const sc_lv<72> ap_ST_fsm_state4;
    static const sc_lv<72> ap_ST_fsm_state5;
    static const sc_lv<72> ap_ST_fsm_state6;
    static const sc_lv<72> ap_ST_fsm_state7;
    static const sc_lv<72> ap_ST_fsm_state8;
    static const sc_lv<72> ap_ST_fsm_state9;
    static const sc_lv<72> ap_ST_fsm_state10;
    static const sc_lv<72> ap_ST_fsm_state11;
    static const sc_lv<72> ap_ST_fsm_state12;
    static const sc_lv<72> ap_ST_fsm_state13;
    static const sc_lv<72> ap_ST_fsm_state14;
    static const sc_lv<72> ap_ST_fsm_state15;
    static const sc_lv<72> ap_ST_fsm_state16;
    static const sc_lv<72> ap_ST_fsm_state17;
    static const sc_lv<72> ap_ST_fsm_state18;
    static const sc_lv<72> ap_ST_fsm_state19;
    static const sc_lv<72> ap_ST_fsm_state20;
    static const sc_lv<72> ap_ST_fsm_state21;
    static const sc_lv<72> ap_ST_fsm_state22;
    static const sc_lv<72> ap_ST_fsm_state23;
    static const sc_lv<72> ap_ST_fsm_state24;
    static const sc_lv<72> ap_ST_fsm_state25;
    static const sc_lv<72> ap_ST_fsm_state26;
    static const sc_lv<72> ap_ST_fsm_state27;
    static const sc_lv<72> ap_ST_fsm_state28;
    static const sc_lv<72> ap_ST_fsm_state29;
    static const sc_lv<72> ap_ST_fsm_state30;
    static const sc_lv<72> ap_ST_fsm_state31;
    static const sc_lv<72> ap_ST_fsm_state32;
    static const sc_lv<72> ap_ST_fsm_state33;
    static const sc_lv<72> ap_ST_fsm_state34;
    static const sc_lv<72> ap_ST_fsm_state35;
    static const sc_lv<72> ap_ST_fsm_state36;
    static const sc_lv<72> ap_ST_fsm_state37;
    static const sc_lv<72> ap_ST_fsm_state38;
    static const sc_lv<72> ap_ST_fsm_state39;
    static const sc_lv<72> ap_ST_fsm_state40;
    static const sc_lv<72> ap_ST_fsm_state41;
    static const sc_lv<72> ap_ST_fsm_state42;
    static const sc_lv<72> ap_ST_fsm_state43;
    static const sc_lv<72> ap_ST_fsm_state44;
    static const sc_lv<72> ap_ST_fsm_state45;
    static const sc_lv<72> ap_ST_fsm_state46;
    static const sc_lv<72> ap_ST_fsm_state47;
    static const sc_lv<72> ap_ST_fsm_state48;
    static const sc_lv<72> ap_ST_fsm_pp0_stage0;
    static const sc_lv<72> ap_ST_fsm_pp0_stage1;
    static const sc_lv<72> ap_ST_fsm_pp0_stage2;
    static const sc_lv<72> ap_ST_fsm_pp0_stage3;
    static const sc_lv<72> ap_ST_fsm_pp0_stage4;
    static const sc_lv<72> ap_ST_fsm_pp0_stage5;
    static const sc_lv<72> ap_ST_fsm_pp0_stage6;
    static const sc_lv<72> ap_ST_fsm_pp0_stage7;
    static const sc_lv<72> ap_ST_fsm_pp0_stage8;
    static const sc_lv<72> ap_ST_fsm_pp0_stage9;
    static const sc_lv<72> ap_ST_fsm_pp0_stage10;
    static const sc_lv<72> ap_ST_fsm_pp0_stage11;
    static const sc_lv<72> ap_ST_fsm_pp0_stage12;
    static const sc_lv<72> ap_ST_fsm_pp0_stage13;
    static const sc_lv<72> ap_ST_fsm_pp0_stage14;
    static const sc_lv<72> ap_ST_fsm_pp0_stage15;
    static const sc_lv<72> ap_ST_fsm_pp0_stage16;
    static const sc_lv<72> ap_ST_fsm_pp0_stage17;
    static const sc_lv<72> ap_ST_fsm_pp0_stage18;
    static const sc_lv<72> ap_ST_fsm_pp0_stage19;
    static const sc_lv<72> ap_ST_fsm_pp0_stage20;
    static const sc_lv<72> ap_ST_fsm_pp0_stage21;
    static const sc_lv<72> ap_ST_fsm_pp0_stage22;
    static const sc_lv<72> ap_ST_fsm_state73;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3A;
    static const sc_lv<32> ap_const_lv32_43;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_46;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_47;
    static const sc_lv<64> ap_const_lv64_C000000000000000;
    static const sc_lv<32> ap_const_lv32_2B;
    static const sc_lv<32> ap_const_lv32_36;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<64> ap_const_lv64_4008000000000000;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<64> ap_const_lv64_4000000000000000;
    static const sc_lv<64> ap_const_lv64_4084000000000000;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<64> ap_const_lv64_407E000000000000;
    static const sc_lv<64> ap_const_lv64_4010000000000000;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<24> ap_const_lv24_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<32> ap_const_lv32_101;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_2;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage10();
    void thread_ap_CS_fsm_pp0_stage14();
    void thread_ap_CS_fsm_pp0_stage19();
    void thread_ap_CS_fsm_pp0_stage22();
    void thread_ap_CS_fsm_pp0_stage5();
    void thread_ap_CS_fsm_pp0_stage6();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state37();
    void thread_ap_CS_fsm_state38();
    void thread_ap_CS_fsm_state43();
    void thread_ap_CS_fsm_state44();
    void thread_ap_CS_fsm_state48();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state73();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_grp_fu_122_opcode();
    void thread_grp_fu_122_p0();
    void thread_grp_fu_122_p1();
    void thread_grp_fu_127_p0();
    void thread_grp_fu_127_p1();
    void thread_grp_fu_133_p0();
    void thread_grp_fu_133_p1();
    void thread_grp_fu_138_p0();
    void thread_grp_fu_138_p1();
    void thread_icmp_fu_216_p2();
    void thread_notlhs_fu_246_p2();
    void thread_notrhs_fu_252_p2();
    void thread_t_phi_fu_102_p4();
    void thread_tmp_14_to_int_fu_228_p1();
    void thread_tmp_16_fu_270_p3();
    void thread_tmp_17_fu_232_p4();
    void thread_tmp_18_fu_242_p1();
    void thread_tmp_19_fu_258_p2();
    void thread_tmp_21_fu_264_p2();
    void thread_tmp_6_op_fu_222_p2();
    void thread_tmp_6_phi_fu_90_p4();
    void thread_tmp_7_fu_206_p4();
    void thread_y_phi_fu_114_p4();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
