// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Mat2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        img_1_data_stream_0_dout,
        img_1_data_stream_0_empty_n,
        img_1_data_stream_0_read,
        img_1_data_stream_1_dout,
        img_1_data_stream_1_empty_n,
        img_1_data_stream_1_read,
        video_out_TDATA,
        video_out_TVALID,
        video_out_TREADY,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST
);

parameter    ap_ST_fsm_state1 = 4'b1;
parameter    ap_ST_fsm_state2 = 4'b10;
parameter    ap_ST_fsm_pp0_stage0 = 4'b100;
parameter    ap_ST_fsm_state6 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] rows;
input  [31:0] cols;
input  [7:0] img_1_data_stream_0_dout;
input   img_1_data_stream_0_empty_n;
output   img_1_data_stream_0_read;
input  [7:0] img_1_data_stream_1_dout;
input   img_1_data_stream_1_empty_n;
output   img_1_data_stream_1_read;
output  [15:0] video_out_TDATA;
output   video_out_TVALID;
input   video_out_TREADY;
output  [1:0] video_out_TKEEP;
output  [1:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_1_data_stream_0_read;
reg img_1_data_stream_1_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [15:0] video_out_V_data_V_1_data_out;
reg    video_out_V_data_V_1_vld_in;
wire    video_out_V_data_V_1_vld_out;
wire    video_out_V_data_V_1_ack_in;
wire    video_out_V_data_V_1_ack_out;
reg   [15:0] video_out_V_data_V_1_payload_A;
reg   [15:0] video_out_V_data_V_1_payload_B;
reg    video_out_V_data_V_1_sel_rd;
reg    video_out_V_data_V_1_sel_wr;
wire    video_out_V_data_V_1_sel;
wire    video_out_V_data_V_1_load_A;
wire    video_out_V_data_V_1_load_B;
reg   [1:0] video_out_V_data_V_1_state;
wire    video_out_V_data_V_1_state_cmp_full;
wire   [1:0] video_out_V_keep_V_1_data_out;
reg    video_out_V_keep_V_1_vld_in;
wire    video_out_V_keep_V_1_vld_out;
wire    video_out_V_keep_V_1_ack_in;
wire    video_out_V_keep_V_1_ack_out;
reg    video_out_V_keep_V_1_sel_rd;
wire    video_out_V_keep_V_1_sel;
reg   [1:0] video_out_V_keep_V_1_state;
wire   [1:0] video_out_V_strb_V_1_data_out;
reg    video_out_V_strb_V_1_vld_in;
wire    video_out_V_strb_V_1_vld_out;
wire    video_out_V_strb_V_1_ack_in;
wire    video_out_V_strb_V_1_ack_out;
reg    video_out_V_strb_V_1_sel_rd;
wire    video_out_V_strb_V_1_sel;
reg   [1:0] video_out_V_strb_V_1_state;
reg   [0:0] video_out_V_user_V_1_data_out;
reg    video_out_V_user_V_1_vld_in;
wire    video_out_V_user_V_1_vld_out;
wire    video_out_V_user_V_1_ack_in;
wire    video_out_V_user_V_1_ack_out;
reg   [0:0] video_out_V_user_V_1_payload_A;
reg   [0:0] video_out_V_user_V_1_payload_B;
reg    video_out_V_user_V_1_sel_rd;
reg    video_out_V_user_V_1_sel_wr;
wire    video_out_V_user_V_1_sel;
wire    video_out_V_user_V_1_load_A;
wire    video_out_V_user_V_1_load_B;
reg   [1:0] video_out_V_user_V_1_state;
wire    video_out_V_user_V_1_state_cmp_full;
reg   [0:0] video_out_V_last_V_1_data_out;
reg    video_out_V_last_V_1_vld_in;
wire    video_out_V_last_V_1_vld_out;
wire    video_out_V_last_V_1_ack_in;
wire    video_out_V_last_V_1_ack_out;
reg   [0:0] video_out_V_last_V_1_payload_A;
reg   [0:0] video_out_V_last_V_1_payload_B;
reg    video_out_V_last_V_1_sel_rd;
reg    video_out_V_last_V_1_sel_wr;
wire    video_out_V_last_V_1_sel;
wire    video_out_V_last_V_1_load_A;
wire    video_out_V_last_V_1_load_B;
reg   [1:0] video_out_V_last_V_1_state;
wire    video_out_V_last_V_1_state_cmp_full;
wire   [0:0] video_out_V_id_V_1_data_out;
reg    video_out_V_id_V_1_vld_in;
wire    video_out_V_id_V_1_vld_out;
wire    video_out_V_id_V_1_ack_in;
wire    video_out_V_id_V_1_ack_out;
reg    video_out_V_id_V_1_sel_rd;
wire    video_out_V_id_V_1_sel;
reg   [1:0] video_out_V_id_V_1_state;
wire   [0:0] video_out_V_dest_V_1_data_out;
reg    video_out_V_dest_V_1_vld_in;
wire    video_out_V_dest_V_1_vld_out;
wire    video_out_V_dest_V_1_ack_in;
wire    video_out_V_dest_V_1_ack_out;
reg    video_out_V_dest_V_1_sel_rd;
wire    video_out_V_dest_V_1_sel;
reg   [1:0] video_out_V_dest_V_1_state;
reg    img_1_data_stream_0_blk_n;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] exitcond_i_i_reg_268;
reg    img_1_data_stream_1_blk_n;
reg    video_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268;
reg   [10:0] p_1_i_i_reg_162;
wire   [10:0] tmp_fu_173_p1;
wire   [10:0] tmp_26_fu_177_p1;
wire   [10:0] r_V_fu_181_p2;
wire   [0:0] exitcond1_i_i_fu_192_p2;
wire   [0:0] ap_CS_fsm_state2;
reg    ap_condition_499;
wire   [10:0] i_V_fu_197_p2;
reg   [10:0] i_V_reg_263;
wire   [0:0] exitcond_i_i_fu_203_p2;
reg    ap_condition_514;
wire   [10:0] j_V_fu_208_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] axi_last_V_fu_214_p2;
reg   [0:0] axi_last_V_reg_277;
wire   [15:0] tmp_data_V_fu_223_p3;
reg   [10:0] p_i_i_reg_151;
wire   [0:0] ap_CS_fsm_state6;
reg   [0:0] tmp_user_V_fu_94;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'b1;
#0 video_out_V_data_V_1_sel_rd = 1'b0;
#0 video_out_V_data_V_1_sel_wr = 1'b0;
#0 video_out_V_data_V_1_state = 2'b00;
#0 video_out_V_keep_V_1_sel_rd = 1'b0;
#0 video_out_V_keep_V_1_state = 2'b00;
#0 video_out_V_strb_V_1_sel_rd = 1'b0;
#0 video_out_V_strb_V_1_state = 2'b00;
#0 video_out_V_user_V_1_sel_rd = 1'b0;
#0 video_out_V_user_V_1_sel_wr = 1'b0;
#0 video_out_V_user_V_1_state = 2'b00;
#0 video_out_V_last_V_1_sel_rd = 1'b0;
#0 video_out_V_last_V_1_sel_wr = 1'b0;
#0 video_out_V_last_V_1_state = 2'b00;
#0 video_out_V_id_V_1_sel_rd = 1'b0;
#0 video_out_V_id_V_1_state = 2'b00;
#0 video_out_V_dest_V_1_sel_rd = 1'b0;
#0 video_out_V_dest_V_1_state = 2'b00;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & ~(1'b0 == exitcond_i_i_fu_203_p2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & (1'b0 == exitcond_i_i_fu_203_p2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & ~(1'b0 == exitcond_i_i_fu_203_p2)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_data_V_1_ack_out) & (1'b1 == video_out_V_data_V_1_vld_out))) begin
            video_out_V_data_V_1_sel_rd <= ~video_out_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_data_V_1_vld_in) & (1'b1 == video_out_V_data_V_1_ack_in))) begin
            video_out_V_data_V_1_sel_wr <= ~video_out_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_data_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_data_V_1_vld_in) & (1'b1 == video_out_V_data_V_1_ack_out) & (video_out_V_data_V_1_state == ap_const_lv2_3)) | ((1'b0 == video_out_V_data_V_1_vld_in) & (video_out_V_data_V_1_state == ap_const_lv2_2)))) begin
            video_out_V_data_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_data_V_1_vld_in) & (1'b0 == video_out_V_data_V_1_ack_out) & (video_out_V_data_V_1_state == ap_const_lv2_3)) | ((1'b0 == video_out_V_data_V_1_ack_out) & (video_out_V_data_V_1_state == ap_const_lv2_1)))) begin
            video_out_V_data_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_data_V_1_vld_in) & (video_out_V_data_V_1_state == ap_const_lv2_2)) | ((1'b1 == video_out_V_data_V_1_ack_out) & (video_out_V_data_V_1_state == ap_const_lv2_1)) | ((video_out_V_data_V_1_state == ap_const_lv2_3) & ~((1'b1 == video_out_V_data_V_1_vld_in) & (1'b0 == video_out_V_data_V_1_ack_out)) & ~((1'b0 == video_out_V_data_V_1_vld_in) & (1'b1 == video_out_V_data_V_1_ack_out))))) begin
            video_out_V_data_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_data_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_dest_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_dest_V_1_ack_out) & (1'b1 == video_out_V_dest_V_1_vld_out))) begin
            video_out_V_dest_V_1_sel_rd <= ~video_out_V_dest_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_dest_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_dest_V_1_vld_in) & (1'b1 == video_out_V_dest_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_dest_V_1_state)) | ((1'b0 == video_out_V_dest_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_dest_V_1_state)))) begin
            video_out_V_dest_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_dest_V_1_vld_in) & (1'b0 == video_out_V_dest_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_dest_V_1_state)) | ((1'b0 == video_out_V_dest_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_dest_V_1_state)))) begin
            video_out_V_dest_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_dest_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_dest_V_1_state)) | ((1'b1 == video_out_V_dest_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_dest_V_1_state)) | ((ap_const_lv2_3 == video_out_V_dest_V_1_state) & ~((1'b1 == video_out_V_dest_V_1_vld_in) & (1'b0 == video_out_V_dest_V_1_ack_out)) & ~((1'b0 == video_out_V_dest_V_1_vld_in) & (1'b1 == video_out_V_dest_V_1_ack_out))))) begin
            video_out_V_dest_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_dest_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_id_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_id_V_1_ack_out) & (1'b1 == video_out_V_id_V_1_vld_out))) begin
            video_out_V_id_V_1_sel_rd <= ~video_out_V_id_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_id_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_id_V_1_vld_in) & (1'b1 == video_out_V_id_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_id_V_1_state)) | ((1'b0 == video_out_V_id_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_id_V_1_state)))) begin
            video_out_V_id_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_id_V_1_vld_in) & (1'b0 == video_out_V_id_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_id_V_1_state)) | ((1'b0 == video_out_V_id_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_id_V_1_state)))) begin
            video_out_V_id_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_id_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_id_V_1_state)) | ((1'b1 == video_out_V_id_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_id_V_1_state)) | ((ap_const_lv2_3 == video_out_V_id_V_1_state) & ~((1'b1 == video_out_V_id_V_1_vld_in) & (1'b0 == video_out_V_id_V_1_ack_out)) & ~((1'b0 == video_out_V_id_V_1_vld_in) & (1'b1 == video_out_V_id_V_1_ack_out))))) begin
            video_out_V_id_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_id_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_keep_V_1_ack_out) & (1'b1 == video_out_V_keep_V_1_vld_out))) begin
            video_out_V_keep_V_1_sel_rd <= ~video_out_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_keep_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_keep_V_1_vld_in) & (1'b1 == video_out_V_keep_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_keep_V_1_state)) | ((1'b0 == video_out_V_keep_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_keep_V_1_state)))) begin
            video_out_V_keep_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_keep_V_1_vld_in) & (1'b0 == video_out_V_keep_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_keep_V_1_state)) | ((1'b0 == video_out_V_keep_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_keep_V_1_state)))) begin
            video_out_V_keep_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_keep_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_keep_V_1_state)) | ((1'b1 == video_out_V_keep_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_keep_V_1_state)) | ((ap_const_lv2_3 == video_out_V_keep_V_1_state) & ~((1'b1 == video_out_V_keep_V_1_vld_in) & (1'b0 == video_out_V_keep_V_1_ack_out)) & ~((1'b0 == video_out_V_keep_V_1_vld_in) & (1'b1 == video_out_V_keep_V_1_ack_out))))) begin
            video_out_V_keep_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_keep_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_last_V_1_ack_out) & (1'b1 == video_out_V_last_V_1_vld_out))) begin
            video_out_V_last_V_1_sel_rd <= ~video_out_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_last_V_1_vld_in) & (1'b1 == video_out_V_last_V_1_ack_in))) begin
            video_out_V_last_V_1_sel_wr <= ~video_out_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_last_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_last_V_1_vld_in) & (1'b1 == video_out_V_last_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_last_V_1_state)) | ((1'b0 == video_out_V_last_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_last_V_1_state)))) begin
            video_out_V_last_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_last_V_1_vld_in) & (1'b0 == video_out_V_last_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_last_V_1_state)) | ((1'b0 == video_out_V_last_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_last_V_1_state)))) begin
            video_out_V_last_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_last_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_last_V_1_state)) | ((1'b1 == video_out_V_last_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_last_V_1_state)) | ((ap_const_lv2_3 == video_out_V_last_V_1_state) & ~((1'b1 == video_out_V_last_V_1_vld_in) & (1'b0 == video_out_V_last_V_1_ack_out)) & ~((1'b0 == video_out_V_last_V_1_vld_in) & (1'b1 == video_out_V_last_V_1_ack_out))))) begin
            video_out_V_last_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_last_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_strb_V_1_ack_out) & (1'b1 == video_out_V_strb_V_1_vld_out))) begin
            video_out_V_strb_V_1_sel_rd <= ~video_out_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_strb_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_strb_V_1_vld_in) & (1'b1 == video_out_V_strb_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_strb_V_1_state)) | ((1'b0 == video_out_V_strb_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_strb_V_1_state)))) begin
            video_out_V_strb_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_strb_V_1_vld_in) & (1'b0 == video_out_V_strb_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_strb_V_1_state)) | ((1'b0 == video_out_V_strb_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_strb_V_1_state)))) begin
            video_out_V_strb_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_strb_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_strb_V_1_state)) | ((1'b1 == video_out_V_strb_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_strb_V_1_state)) | ((ap_const_lv2_3 == video_out_V_strb_V_1_state) & ~((1'b1 == video_out_V_strb_V_1_vld_in) & (1'b0 == video_out_V_strb_V_1_ack_out)) & ~((1'b0 == video_out_V_strb_V_1_vld_in) & (1'b1 == video_out_V_strb_V_1_ack_out))))) begin
            video_out_V_strb_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_strb_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_user_V_1_ack_out) & (1'b1 == video_out_V_user_V_1_vld_out))) begin
            video_out_V_user_V_1_sel_rd <= ~video_out_V_user_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == video_out_V_user_V_1_vld_in) & (1'b1 == video_out_V_user_V_1_ack_in))) begin
            video_out_V_user_V_1_sel_wr <= ~video_out_V_user_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        video_out_V_user_V_1_state <= ap_const_lv2_0;
    end else begin
        if ((((1'b0 == video_out_V_user_V_1_vld_in) & (1'b1 == video_out_V_user_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_user_V_1_state)) | ((1'b0 == video_out_V_user_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_user_V_1_state)))) begin
            video_out_V_user_V_1_state <= ap_const_lv2_2;
        end else if ((((1'b1 == video_out_V_user_V_1_vld_in) & (1'b0 == video_out_V_user_V_1_ack_out) & (ap_const_lv2_3 == video_out_V_user_V_1_state)) | ((1'b0 == video_out_V_user_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_user_V_1_state)))) begin
            video_out_V_user_V_1_state <= ap_const_lv2_1;
        end else if ((((1'b1 == video_out_V_user_V_1_vld_in) & (ap_const_lv2_2 == video_out_V_user_V_1_state)) | ((1'b1 == video_out_V_user_V_1_ack_out) & (ap_const_lv2_1 == video_out_V_user_V_1_state)) | ((ap_const_lv2_3 == video_out_V_user_V_1_state) & ~((1'b1 == video_out_V_user_V_1_vld_in) & (1'b0 == video_out_V_user_V_1_ack_out)) & ~((1'b0 == video_out_V_user_V_1_vld_in) & (1'b1 == video_out_V_user_V_1_ack_out))))) begin
            video_out_V_user_V_1_state <= ap_const_lv2_3;
        end else begin
            video_out_V_user_V_1_state <= ap_const_lv2_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b0 == exitcond_i_i_fu_203_p2))) begin
        p_1_i_i_reg_162 <= j_V_fu_208_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
        p_1_i_i_reg_162 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_CS_fsm_state1 == 1'b1) & ~((ap_start == 1'b0) | (ap_done_reg == 1'b1)))) begin
        p_i_i_reg_151 <= ap_const_lv11_0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_i_i_reg_151 <= i_V_reg_263;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        tmp_user_V_fu_94 <= 1'b0;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~((ap_start == 1'b0) | (ap_done_reg == 1'b1)))) begin
        tmp_user_V_fu_94 <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268 <= exitcond_i_i_reg_268;
        exitcond_i_i_reg_268 <= exitcond_i_i_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & (1'b0 == exitcond_i_i_fu_203_p2))) begin
        axi_last_V_reg_277 <= axi_last_V_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(ap_condition_499 == 1'b1))) begin
        i_V_reg_263 <= i_V_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_data_V_1_load_A)) begin
        video_out_V_data_V_1_payload_A <= tmp_data_V_fu_223_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_data_V_1_load_B)) begin
        video_out_V_data_V_1_payload_B <= tmp_data_V_fu_223_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_last_V_1_load_A)) begin
        video_out_V_last_V_1_payload_A <= axi_last_V_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_last_V_1_load_B)) begin
        video_out_V_last_V_1_payload_B <= axi_last_V_reg_277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_user_V_1_load_A)) begin
        video_out_V_user_V_1_payload_A <= tmp_user_V_fu_94;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == video_out_V_user_V_1_load_B)) begin
        video_out_V_user_V_1_payload_B <= tmp_user_V_fu_94;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ~(1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268))) begin
        img_1_data_stream_0_blk_n = img_1_data_stream_0_empty_n;
    end else begin
        img_1_data_stream_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        img_1_data_stream_0_read = 1'b1;
    end else begin
        img_1_data_stream_0_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268))) begin
        img_1_data_stream_1_blk_n = img_1_data_stream_1_empty_n;
    end else begin
        img_1_data_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        img_1_data_stream_1_read = 1'b1;
    end else begin
        img_1_data_stream_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268)))) begin
        video_out_TDATA_blk_n = video_out_V_data_V_1_state[1'b1];
    end else begin
        video_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == video_out_V_data_V_1_sel)) begin
        video_out_V_data_V_1_data_out = video_out_V_data_V_1_payload_B;
    end else begin
        video_out_V_data_V_1_data_out = video_out_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_data_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_dest_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_dest_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_id_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_id_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_keep_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == video_out_V_last_V_1_sel)) begin
        video_out_V_last_V_1_data_out = video_out_V_last_V_1_payload_B;
    end else begin
        video_out_V_last_V_1_data_out = video_out_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_last_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_strb_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == video_out_V_user_V_1_sel)) begin
        video_out_V_user_V_1_data_out = video_out_V_user_V_1_payload_B;
    end else begin
        video_out_V_user_V_1_data_out = video_out_V_user_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b0 == exitcond_i_i_reg_268) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))))) begin
        video_out_V_user_V_1_vld_in = 1'b1;
    end else begin
        video_out_V_user_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == exitcond1_i_i_fu_192_p2) & ~(ap_condition_499 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & ~(1'b1 == ap_enable_reg_pp0_iter1)) & ~(~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'b0 == exitcond_i_i_fu_203_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter2) & ~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & ~(1'b1 == ap_enable_reg_pp0_iter1)) | (~(((1'b1 == ap_enable_reg_pp0_iter1) & ((ap_condition_514 == 1'b1) | ((1'b0 == exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in)))) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_pipeline_reg_pp0_iter1_exitcond_i_i_reg_268) & (1'b0 == video_out_V_data_V_1_ack_in))) & (1'b1 == ap_enable_reg_pp0_iter0) & ~(1'b0 == exitcond_i_i_fu_203_p2) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state2 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state6 = ap_CS_fsm[ap_const_lv32_3];

always @ (*) begin
    ap_condition_499 = ((video_out_V_data_V_1_ack_in == 1'b0) | (video_out_V_keep_V_1_ack_in == 1'b0) | (video_out_V_strb_V_1_ack_in == 1'b0) | (video_out_V_user_V_1_ack_in == 1'b0) | (video_out_V_last_V_1_ack_in == 1'b0) | (video_out_V_id_V_1_ack_in == 1'b0) | (video_out_V_dest_V_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_condition_514 = (((1'b0 == exitcond_i_i_reg_268) & (img_1_data_stream_0_empty_n == 1'b0)) | ((1'b0 == exitcond_i_i_reg_268) & (img_1_data_stream_1_empty_n == 1'b0)));
end

assign axi_last_V_fu_214_p2 = ((p_1_i_i_reg_162 == r_V_fu_181_p2) ? 1'b1 : 1'b0);

assign exitcond1_i_i_fu_192_p2 = ((p_i_i_reg_151 == tmp_fu_173_p1) ? 1'b1 : 1'b0);

assign exitcond_i_i_fu_203_p2 = ((p_1_i_i_reg_162 == tmp_26_fu_177_p1) ? 1'b1 : 1'b0);

assign i_V_fu_197_p2 = (p_i_i_reg_151 + ap_const_lv11_1);

assign j_V_fu_208_p2 = (p_1_i_i_reg_162 + ap_const_lv11_1);

assign r_V_fu_181_p2 = ($signed(ap_const_lv11_7FF) + $signed(tmp_26_fu_177_p1));

assign tmp_26_fu_177_p1 = cols[10:0];

assign tmp_data_V_fu_223_p3 = {{img_1_data_stream_1_dout}, {img_1_data_stream_0_dout}};

assign tmp_fu_173_p1 = rows[10:0];

assign video_out_TDATA = video_out_V_data_V_1_data_out;

assign video_out_TDEST = video_out_V_dest_V_1_data_out;

assign video_out_TID = video_out_V_id_V_1_data_out;

assign video_out_TKEEP = video_out_V_keep_V_1_data_out;

assign video_out_TLAST = video_out_V_last_V_1_data_out;

assign video_out_TSTRB = video_out_V_strb_V_1_data_out;

assign video_out_TUSER = video_out_V_user_V_1_data_out;

assign video_out_TVALID = video_out_V_dest_V_1_state[1'b0];

assign video_out_V_data_V_1_ack_in = video_out_V_data_V_1_state[1'b1];

assign video_out_V_data_V_1_ack_out = video_out_TREADY;

assign video_out_V_data_V_1_load_A = (video_out_V_data_V_1_state_cmp_full & ~video_out_V_data_V_1_sel_wr);

assign video_out_V_data_V_1_load_B = (video_out_V_data_V_1_sel_wr & video_out_V_data_V_1_state_cmp_full);

assign video_out_V_data_V_1_sel = video_out_V_data_V_1_sel_rd;

assign video_out_V_data_V_1_state_cmp_full = ((video_out_V_data_V_1_state != ap_const_lv2_1) ? 1'b1 : 1'b0);

assign video_out_V_data_V_1_vld_out = video_out_V_data_V_1_state[1'b0];

assign video_out_V_dest_V_1_ack_in = video_out_V_dest_V_1_state[1'b1];

assign video_out_V_dest_V_1_ack_out = video_out_TREADY;

assign video_out_V_dest_V_1_data_out = 1'b0;

assign video_out_V_dest_V_1_sel = video_out_V_dest_V_1_sel_rd;

assign video_out_V_dest_V_1_vld_out = video_out_V_dest_V_1_state[1'b0];

assign video_out_V_id_V_1_ack_in = video_out_V_id_V_1_state[1'b1];

assign video_out_V_id_V_1_ack_out = video_out_TREADY;

assign video_out_V_id_V_1_data_out = 1'b0;

assign video_out_V_id_V_1_sel = video_out_V_id_V_1_sel_rd;

assign video_out_V_id_V_1_vld_out = video_out_V_id_V_1_state[1'b0];

assign video_out_V_keep_V_1_ack_in = video_out_V_keep_V_1_state[1'b1];

assign video_out_V_keep_V_1_ack_out = video_out_TREADY;

assign video_out_V_keep_V_1_data_out = ap_const_lv2_3;

assign video_out_V_keep_V_1_sel = video_out_V_keep_V_1_sel_rd;

assign video_out_V_keep_V_1_vld_out = video_out_V_keep_V_1_state[1'b0];

assign video_out_V_last_V_1_ack_in = video_out_V_last_V_1_state[1'b1];

assign video_out_V_last_V_1_ack_out = video_out_TREADY;

assign video_out_V_last_V_1_load_A = (video_out_V_last_V_1_state_cmp_full & ~video_out_V_last_V_1_sel_wr);

assign video_out_V_last_V_1_load_B = (video_out_V_last_V_1_sel_wr & video_out_V_last_V_1_state_cmp_full);

assign video_out_V_last_V_1_sel = video_out_V_last_V_1_sel_rd;

assign video_out_V_last_V_1_state_cmp_full = ((video_out_V_last_V_1_state != ap_const_lv2_1) ? 1'b1 : 1'b0);

assign video_out_V_last_V_1_vld_out = video_out_V_last_V_1_state[1'b0];

assign video_out_V_strb_V_1_ack_in = video_out_V_strb_V_1_state[1'b1];

assign video_out_V_strb_V_1_ack_out = video_out_TREADY;

assign video_out_V_strb_V_1_data_out = ap_const_lv2_0;

assign video_out_V_strb_V_1_sel = video_out_V_strb_V_1_sel_rd;

assign video_out_V_strb_V_1_vld_out = video_out_V_strb_V_1_state[1'b0];

assign video_out_V_user_V_1_ack_in = video_out_V_user_V_1_state[1'b1];

assign video_out_V_user_V_1_ack_out = video_out_TREADY;

assign video_out_V_user_V_1_load_A = (video_out_V_user_V_1_state_cmp_full & ~video_out_V_user_V_1_sel_wr);

assign video_out_V_user_V_1_load_B = (video_out_V_user_V_1_sel_wr & video_out_V_user_V_1_state_cmp_full);

assign video_out_V_user_V_1_sel = video_out_V_user_V_1_sel_rd;

assign video_out_V_user_V_1_state_cmp_full = ((video_out_V_user_V_1_state != ap_const_lv2_1) ? 1'b1 : 1'b0);

assign video_out_V_user_V_1_vld_out = video_out_V_user_V_1_state[1'b0];

endmodule //Mat2AXIvideo
