// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmandelbrot.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMandelbrot_CfgInitialize(XMandelbrot *InstancePtr, XMandelbrot_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMandelbrot_Start(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL) & 0x80;
    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMandelbrot_IsDone(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMandelbrot_IsIdle(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMandelbrot_IsReady(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMandelbrot_EnableAutoRestart(XMandelbrot *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XMandelbrot_DisableAutoRestart(XMandelbrot *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XMandelbrot_Get_return(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XMandelbrot_Set_cx(XMandelbrot *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_CX_DATA, Data);
}

u32 XMandelbrot_Get_cx(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_CX_DATA);
    return Data;
}

void XMandelbrot_Set_cy(XMandelbrot *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_CY_DATA, Data);
}

u32 XMandelbrot_Get_cy(XMandelbrot *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_CY_DATA);
    return Data;
}

void XMandelbrot_InterruptGlobalEnable(XMandelbrot *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_GIE, 1);
}

void XMandelbrot_InterruptGlobalDisable(XMandelbrot *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_GIE, 0);
}

void XMandelbrot_InterruptEnable(XMandelbrot *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_IER);
    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_IER, Register | Mask);
}

void XMandelbrot_InterruptDisable(XMandelbrot *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_IER);
    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_IER, Register & (~Mask));
}

void XMandelbrot_InterruptClear(XMandelbrot *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMandelbrot_WriteReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_ISR, Mask);
}

u32 XMandelbrot_InterruptGetEnabled(XMandelbrot *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_IER);
}

u32 XMandelbrot_InterruptGetStatus(XMandelbrot *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMandelbrot_ReadReg(InstancePtr->Axilites_BaseAddress, XMANDELBROT_AXILITES_ADDR_ISR);
}

