// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#1 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
#1 "<built-in>"
#1 "<command-line>"
#1 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
#1 "/home/raph/zed-design/mandel1/solution1/tb.h" 1


extern int mandelbrot(int cx, int cy) ;
#2 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp" 2




#ifndef HLS_FASTSIM
#5 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"

#ifndef HLS_FASTSIM
#include "apatb_mandelbrot.h"
#endif

#5 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
int main()
{




 return 
#ifndef HLS_FASTSIM
#define mandelbrot AESL_WRAP_mandelbrot
#endif

#11 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"

#ifndef HLS_FASTSIM
#define mandelbrot AESL_WRAP_mandelbrot
#endif

#11 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
mandelbrot
#undef mandelbrot
#11 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"

#undef mandelbrot
#11 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
(00,0);
}
#endif
#12 "/home/raph/zed-design/mandel1/solution1/tb_mandel.cpp"
